### ISSUE TITLE
 Carthage Error

### ISSUE THREAD

**Issue by RookiePyl** [Insta360Develop/CameraSDK-iOS#1]
<img width="571" alt="error" src="https://user-images.githubusercontent.com/15116300/101599686-226a4680-3a35-11eb-8533-620a831df2bd.png">

input my Cartfile:

binary "#INSCoreMedia:By applying for authorization from Insta360#" == 1.25.7
binary "#INSCameraSDK-osc:By applying for authorization from Insta360#" == 2.7.5

terminal show error:

Parse error: invalid URL found for dependency type `binary` in line: binary "#INSCoreMedia:By applying for authorization from Insta360#" == 1.25.7

**Comment by kelvinhkw** [comment]
> <img alt="error" width="571" src="https://user-images.githubusercontent.com/15116300/101599686-226a4680-3a35-11eb-8533-620a831df2bd.png">
> 
> input my Cartfile:
> 
> binary "#INSCoreMedia:By applying for authorization from Insta360#" == 1.25.7
> binary "#INSCameraSDK-osc:By applying for authorization from Insta360#" == 2.7.5
> 
> terminal show error:
> 
> Parse error: invalid URL found for dependency type `binary` in line: binary "#INSCoreMedia:By applying for authorization from Insta360#" == 1.25.7

Hi there, we could only provide our official SDK and documentation after approval. Please submit an application here: https://www.insta360.com/sdk/home
