### ISSUE TITLE
[bug]Runtime error after the latest SDK upgrade

### ISSUE THREAD

**Issue by Sam-IExpress** [Insta360Develop/CameraSDK-iOS#10]
I'm getting this error after upgrading to below versions:
INSCoreMedia == 1.25.20
INSCameraSDK == 2.7.33

`dyld[25898]: Symbol not found: _OBJC_CLASS_$_INSJpegToH264Encoder
  Referenced from: /private/var/containers/Bundle/Application/8252DE7F-63AA-4499-9182-418B3A660442/INSCameraSDK-SampleOC.app/Frameworks/INSCameraSDK.framework/INSCameraSDK
  Expected in: /private/var/containers/Bundle/Application/8252DE7F-63AA-4499-9182-418B3A660442/INSCameraSDK-SampleOC.app/Frameworks/INSCoreMedia.framework/INSCoreMedia
Symbol not found: _OBJC_CLASS_$_INSJpegToH264Encoder
  Referenced from: /private/var/containers/Bundle/Application/8252DE7F-63AA-4499-9182-418B3A660442/INSCameraSDK-SampleOC.app/Frameworks/INSCameraSDK.framework/INSCameraSDK
  Expected in: /private/var/containers/Bundle/Application/8252DE7F-63AA-4499-9182-418B3A660442/INSCameraSDK-SampleOC.app/Frameworks/INSCoreMedia.framework/INSCoreMedia`

**Comment by Sam-IExpress** [comment]
@capjason @kelvinhkw Appreciate if you can look into this.

**Comment by Sam-IExpress** [comment]
I fixed it by downloading the sample project from the developer portal and copy the frameworks to our project. 
Using the cartfile doesn't work, so i believe it is the frameworks hosted on the server doesn't match the version numbers.

**Comment by sssuourabh** [comment]
Hi @Sam-IExpress can we use this SDK in SWIFTUI project ?
