### ISSUE TITLE
ONE RS preview orientation

### ISSUE THREAD

**Issue by Sam-IExpress** [Insta360Develop/CameraSDK-iOS#32]
Hi, when using the sample code, the ONE RS camera's preview is not correct, it is rotated to 90 degrees clockwise.

The official app is showing the correct orientation.

How do I change it to the correct orientation?

**Comment by mordekai91** [comment]
Hi @Sam-IExpress , did you found a solution for this?

**Comment by Sam-IExpress** [comment]
@mordekai91 Just have to manually ajust the rotation euler.
`_renderView.render.rotationEuler = GLKVector3Make(0, 0, M_PI_2);`
